FROM node:6-stretch
WORKDIR /opt
RUN git clone https://github.com/Haishi2016/osb-checker.git
RUN rm /opt/osb-checker/2.13/tests/test/configs/*.json
COPY compliance/config.json /opt/osb-checker/2.13/tests/test/configs/config_mock.json
RUN npm config set package-lock false && npm install --global mocha
WORKDIR /opt/osb-checker/2.13/tests
RUN npm install
COPY compliance/wrapper.sh /opt/osb-checker/2.13/tests/
ENTRYPOINT [ "./wrapper.sh" ]
