FROM golang:1.8.3

ENV GLIDE_VERSION=v0.12.3

RUN curl -sSL https://github.com/Masterminds/glide/releases/download/$GLIDE_VERSION/glide-$GLIDE_VERSION-linux-amd64.tar.gz \
  | tar -vxz -C /usr/local/bin --strip=1 \
  && go get -u github.com/alecthomas/gometalinter \
  && gometalinter --install \
  && mkdir -p /go/src/github.com/Azure/azure-service-broker

WORKDIR /go/src/github.com/Azure/azure-service-broker
