{{- if .Values.registerBroker }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: osba
spec:
  url: http://{{ template "fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  authInfo:
    basic:
      secretRef:
        name: "{{ template "fullname" . }}-auth"
        namespace: {{ .Release.Namespace | quote }}
{{- end }}
