apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: example-postgresql-dbms-instance
  namespace: default
spec:
  clusterServiceClassExternalName: azure-postgresql-9-6-dbms
  clusterServicePlanExternalName: basic
  parameters:
    location: eastus
    resourceGroup: demo
    alias: 95bde4b9-0785-44e2-94a7-e315df1b9779
    firewallRules:
    - startIPAddress: "0.0.0.0"
      endIPAddress: "255.255.255.255"
      name: "AllowAll"
