apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: example-postgresql-database-instance
  namespace: default
spec:
  clusterServiceClassExternalName: azure-postgresql-9-6-database
  clusterServicePlanExternalName: database
  parameters:
    parentAlias: 95bde4b9-0785-44e2-94a7-e315df1b9779
    extensions:
    - uuid-ossp
    - postgis

