apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: example-sql-binding
  namespace: default
spec:
  instanceRef:
    name: example-sql-instance
  secretName: example-sql-secret
