
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: my-cosmosdb-instance
  namespace: default
spec:
  clusterServiceClassExternalName: azure-cosmos-db
  clusterServicePlanExternalName: cosmos-db-sql-api
  parameters:
    location: eastus
    resourceGroup: demo
