
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: my-cosmosdb-instance
  namespace: default
spec:
  clusterServiceClassExternalName: azure-cosmosdb-sql-account
  clusterServicePlanExternalName: account
  parameters:
    location: eastus
    resourceGroup: demo
    consistencyPolicy:
      defaultConsistencyLevel: Eventual
