apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: my-mongodb-binding
  namespace: default
spec:
  instanceRef:
    name: my-mongodb-instance
  secretName: my-mongodb-secret
