package main

const (
	flagHost            = "host"
	flagsHost           = "host, H"
	flagPort            = "port"
	flagsPort           = "port, p"
	flagUsername        = "username"
	flagsUsername       = "username, u"
	flagPassword        = "password"
	flagsPassword       = "password, P"
	flagServiceID       = "service-id"
	flagsServiceID      = "service-id, sid"
	flagPlanID          = "plan-id"
	flagsPlanID         = "plan-id, pid"
	flagInstanceID      = "instance-id"
	flagsInstanceID     = "instance-id, iid"
	flagBindingID       = "binding-id"
	flagsBindingID      = "binding-id, bid"
	flagParameter       = "parameter"
	flagsParameter      = "parameter, param, string-parameter, sparam"
	flagIntParameter    = "int-parameter"
	flagsIntParameter   = "int-parameter, iparam"
	flagFloatParameter  = "float-parameter"
	flagsFloatParameter = "float-parameter, fparam"
	flagBoolParameter   = "bool-parameter"
	flagsBoolParameter  = "bool-parameter, bparam"
	flagTag             = "tag"
	flagOperation       = "operation"
	flagsOperation      = "operation, o"
	flagPoll            = "poll"
)
