package main

const (
	flagHost        = "host"
	flagsHost       = "host, H"
	flagPort        = "port"
	flagsPort       = "port, p"
	flagUsername    = "username"
	flagsUsername   = "username, u"
	flagPassword    = "password"
	flagsPassword   = "password, P"
	flagServiceID   = "service-id"
	flagsServiceID  = "service-id, sid"
	flagPlanID      = "plan-id"
	flagsPlanID     = "plan-id, pid"
	flagInstanceID  = "instance-id"
	flagsInstanceID = "instance-id, iid"
	flagBindingID   = "binding-id"
	flagsBindingID  = "binding-id, bid"
	flagParameters  = "parameters"
	flagsParameters = "parameters, params"
	flagOperation   = "operation"
	flagsOperation  = "operation, o"
	flagPoll        = "poll"
	flagSSL         = "ssl"
	flagsSSL        = "ssl, s"
	flagInsecure    = "insecure"
	flagsInsecure   = "insecure, i"
)
