apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: example-mysql-dbms-instance
  namespace: default
spec:
  clusterServiceClassExternalName: azure-mysql-5-7-dbms
  clusterServicePlanExternalName: basic
  parameters:
    location: eastus
    resourceGroup: demo
    alias: 71b6b6c4-5271-47d3-8188-51e69fba914e
    firewallRules:
    - startIPAddress: "0.0.0.0"
      endIPAddress: "255.255.255.255"
      name: "AllowAll"
